name: Continuous integration

on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint:
    name: Lint
    runs-on: "ubuntu-latest"
    steps:

    - name: Checkout repo
      uses: actions/checkout@v6

    - name: Setup UV
      uses: astral-sh/setup-uv@v7
      with:
        python-version: "3.13"

    - name: Install dependencies
      run: |
        uv sync --extra dev

    - name: Run ruff checks
      run: |
        uv run ruff check .
